api_platform:
  formats:
    json: ['application/json']
    jsonld: ['application/ld+json']

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header

  title: 'ProjetWeb API'
  version: '1.0.0'